#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMT_MVC.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dml_internal_db")]
	public partial class DCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLeave_Management_Approval_Matrix(Leave_Management_Approval_Matrix instance);
    partial void UpdateLeave_Management_Approval_Matrix(Leave_Management_Approval_Matrix instance);
    partial void DeleteLeave_Management_Approval_Matrix(Leave_Management_Approval_Matrix instance);
    partial void InsertLeave_Management_Leave_Type(Leave_Management_Leave_Type instance);
    partial void UpdateLeave_Management_Leave_Type(Leave_Management_Leave_Type instance);
    partial void DeleteLeave_Management_Leave_Type(Leave_Management_Leave_Type instance);
    partial void InsertLeave_Management_Leave_Allowance(Leave_Management_Leave_Allowance instance);
    partial void UpdateLeave_Management_Leave_Allowance(Leave_Management_Leave_Allowance instance);
    partial void DeleteLeave_Management_Leave_Allowance(Leave_Management_Leave_Allowance instance);
    partial void InsertLeave_Management_Leave_Taken(Leave_Management_Leave_Taken instance);
    partial void UpdateLeave_Management_Leave_Taken(Leave_Management_Leave_Taken instance);
    partial void DeleteLeave_Management_Leave_Taken(Leave_Management_Leave_Taken instance);
    partial void InsertInnovation_Management_User(Innovation_Management_User instance);
    partial void UpdateInnovation_Management_User(Innovation_Management_User instance);
    partial void DeleteInnovation_Management_User(Innovation_Management_User instance);
    #endregion
		
		public DCDataContext() : 
				base(global::LMT_MVC.Properties.Settings.Default.CS, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Leave_Management_Approval_Matrix> Leave_Management_Approval_Matrixes
		{
			get
			{
				return this.GetTable<Leave_Management_Approval_Matrix>();
			}
		}
		
		public System.Data.Linq.Table<Leave_Management_Leave_Type> Leave_Management_Leave_Types
		{
			get
			{
				return this.GetTable<Leave_Management_Leave_Type>();
			}
		}
		
		public System.Data.Linq.Table<Leave_Management_Leave_Allowance> Leave_Management_Leave_Allowances
		{
			get
			{
				return this.GetTable<Leave_Management_Leave_Allowance>();
			}
		}
		
		public System.Data.Linq.Table<Leave_Management_Leave_Taken> Leave_Management_Leave_Takens
		{
			get
			{
				return this.GetTable<Leave_Management_Leave_Taken>();
			}
		}
		
		public System.Data.Linq.Table<Innovation_Management_User> Innovation_Management_Users
		{
			get
			{
				return this.GetTable<Innovation_Management_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leave_Management_Approval_Matrix")]
	public partial class Leave_Management_Approval_Matrix : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pk_approval_id;
		
		private System.Nullable<int> _fk_requestor_id;
		
		private System.Nullable<int> _fk_approver_id;
		
		private EntityRef<Innovation_Management_User> _Innovation_Management_User;
		
		private EntityRef<Innovation_Management_User> _Innovation_Management_User1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_approval_idChanging(int value);
    partial void Onpk_approval_idChanged();
    partial void Onfk_requestor_idChanging(System.Nullable<int> value);
    partial void Onfk_requestor_idChanged();
    partial void Onfk_approver_idChanging(System.Nullable<int> value);
    partial void Onfk_approver_idChanged();
    #endregion
		
		public Leave_Management_Approval_Matrix()
		{
			this._Innovation_Management_User = default(EntityRef<Innovation_Management_User>);
			this._Innovation_Management_User1 = default(EntityRef<Innovation_Management_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_approval_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pk_approval_id
		{
			get
			{
				return this._pk_approval_id;
			}
			set
			{
				if ((this._pk_approval_id != value))
				{
					this.Onpk_approval_idChanging(value);
					this.SendPropertyChanging();
					this._pk_approval_id = value;
					this.SendPropertyChanged("pk_approval_id");
					this.Onpk_approval_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_requestor_id", DbType="Int")]
		public System.Nullable<int> fk_requestor_id
		{
			get
			{
				return this._fk_requestor_id;
			}
			set
			{
				if ((this._fk_requestor_id != value))
				{
					if (this._Innovation_Management_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_requestor_idChanging(value);
					this.SendPropertyChanging();
					this._fk_requestor_id = value;
					this.SendPropertyChanged("fk_requestor_id");
					this.Onfk_requestor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_approver_id", DbType="Int")]
		public System.Nullable<int> fk_approver_id
		{
			get
			{
				return this._fk_approver_id;
			}
			set
			{
				if ((this._fk_approver_id != value))
				{
					if (this._Innovation_Management_User1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_approver_idChanging(value);
					this.SendPropertyChanging();
					this._fk_approver_id = value;
					this.SendPropertyChanged("fk_approver_id");
					this.Onfk_approver_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Approval_Matrix", Storage="_Innovation_Management_User", ThisKey="fk_requestor_id", OtherKey="pk_user_id", IsForeignKey=true)]
		public Innovation_Management_User Innovation_Management_User
		{
			get
			{
				return this._Innovation_Management_User.Entity;
			}
			set
			{
				Innovation_Management_User previousValue = this._Innovation_Management_User.Entity;
				if (((previousValue != value) 
							|| (this._Innovation_Management_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Innovation_Management_User.Entity = null;
						previousValue.Leave_Management_Approval_Matrixes.Remove(this);
					}
					this._Innovation_Management_User.Entity = value;
					if ((value != null))
					{
						value.Leave_Management_Approval_Matrixes.Add(this);
						this._fk_requestor_id = value.pk_user_id;
					}
					else
					{
						this._fk_requestor_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Innovation_Management_User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Approval_Matrix1", Storage="_Innovation_Management_User1", ThisKey="fk_approver_id", OtherKey="pk_user_id", IsForeignKey=true)]
		public Innovation_Management_User Innovation_Management_User1
		{
			get
			{
				return this._Innovation_Management_User1.Entity;
			}
			set
			{
				Innovation_Management_User previousValue = this._Innovation_Management_User1.Entity;
				if (((previousValue != value) 
							|| (this._Innovation_Management_User1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Innovation_Management_User1.Entity = null;
						previousValue.Leave_Management_Approval_Matrixes1.Remove(this);
					}
					this._Innovation_Management_User1.Entity = value;
					if ((value != null))
					{
						value.Leave_Management_Approval_Matrixes1.Add(this);
						this._fk_approver_id = value.pk_user_id;
					}
					else
					{
						this._fk_approver_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Innovation_Management_User1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leave_Management_Leave_Type")]
	public partial class Leave_Management_Leave_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pk_leave_type_id;
		
		private string _leave_type;
		
		private EntitySet<Leave_Management_Leave_Allowance> _Leave_Management_Leave_Allowances;
		
		private EntitySet<Leave_Management_Leave_Taken> _Leave_Management_Leave_Takens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_leave_type_idChanging(int value);
    partial void Onpk_leave_type_idChanged();
    partial void Onleave_typeChanging(string value);
    partial void Onleave_typeChanged();
    #endregion
		
		public Leave_Management_Leave_Type()
		{
			this._Leave_Management_Leave_Allowances = new EntitySet<Leave_Management_Leave_Allowance>(new Action<Leave_Management_Leave_Allowance>(this.attach_Leave_Management_Leave_Allowances), new Action<Leave_Management_Leave_Allowance>(this.detach_Leave_Management_Leave_Allowances));
			this._Leave_Management_Leave_Takens = new EntitySet<Leave_Management_Leave_Taken>(new Action<Leave_Management_Leave_Taken>(this.attach_Leave_Management_Leave_Takens), new Action<Leave_Management_Leave_Taken>(this.detach_Leave_Management_Leave_Takens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_leave_type_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pk_leave_type_id
		{
			get
			{
				return this._pk_leave_type_id;
			}
			set
			{
				if ((this._pk_leave_type_id != value))
				{
					this.Onpk_leave_type_idChanging(value);
					this.SendPropertyChanging();
					this._pk_leave_type_id = value;
					this.SendPropertyChanged("pk_leave_type_id");
					this.Onpk_leave_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leave_type", DbType="NVarChar(MAX)")]
		public string leave_type
		{
			get
			{
				return this._leave_type;
			}
			set
			{
				if ((this._leave_type != value))
				{
					this.Onleave_typeChanging(value);
					this.SendPropertyChanging();
					this._leave_type = value;
					this.SendPropertyChanged("leave_type");
					this.Onleave_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Leave_Management_Leave_Type_Leave_Management_Leave_Allowance", Storage="_Leave_Management_Leave_Allowances", ThisKey="pk_leave_type_id", OtherKey="fk_leave_type_id")]
		public EntitySet<Leave_Management_Leave_Allowance> Leave_Management_Leave_Allowances
		{
			get
			{
				return this._Leave_Management_Leave_Allowances;
			}
			set
			{
				this._Leave_Management_Leave_Allowances.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Leave_Management_Leave_Type_Leave_Management_Leave_Taken", Storage="_Leave_Management_Leave_Takens", ThisKey="pk_leave_type_id", OtherKey="fk_leave_type")]
		public EntitySet<Leave_Management_Leave_Taken> Leave_Management_Leave_Takens
		{
			get
			{
				return this._Leave_Management_Leave_Takens;
			}
			set
			{
				this._Leave_Management_Leave_Takens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Leave_Management_Leave_Allowances(Leave_Management_Leave_Allowance entity)
		{
			this.SendPropertyChanging();
			entity.Leave_Management_Leave_Type = this;
		}
		
		private void detach_Leave_Management_Leave_Allowances(Leave_Management_Leave_Allowance entity)
		{
			this.SendPropertyChanging();
			entity.Leave_Management_Leave_Type = null;
		}
		
		private void attach_Leave_Management_Leave_Takens(Leave_Management_Leave_Taken entity)
		{
			this.SendPropertyChanging();
			entity.Leave_Management_Leave_Type = this;
		}
		
		private void detach_Leave_Management_Leave_Takens(Leave_Management_Leave_Taken entity)
		{
			this.SendPropertyChanging();
			entity.Leave_Management_Leave_Type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leave_Management_Leave_Allowance")]
	public partial class Leave_Management_Leave_Allowance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pk_leave_allowance_id;
		
		private System.Nullable<int> _fk_user_id;
		
		private System.Nullable<int> _fk_leave_type_id;
		
		private string _allowance_year;
		
		private System.Nullable<int> _allowance_entitlement;
		
		private System.Nullable<double> _allowance_taken;
		
		private EntityRef<Leave_Management_Leave_Type> _Leave_Management_Leave_Type;
		
		private EntityRef<Innovation_Management_User> _Innovation_Management_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_leave_allowance_idChanging(int value);
    partial void Onpk_leave_allowance_idChanged();
    partial void Onfk_user_idChanging(System.Nullable<int> value);
    partial void Onfk_user_idChanged();
    partial void Onfk_leave_type_idChanging(System.Nullable<int> value);
    partial void Onfk_leave_type_idChanged();
    partial void Onallowance_yearChanging(string value);
    partial void Onallowance_yearChanged();
    partial void Onallowance_entitlementChanging(System.Nullable<int> value);
    partial void Onallowance_entitlementChanged();
    partial void Onallowance_takenChanging(System.Nullable<double> value);
    partial void Onallowance_takenChanged();
    #endregion
		
		public Leave_Management_Leave_Allowance()
		{
			this._Leave_Management_Leave_Type = default(EntityRef<Leave_Management_Leave_Type>);
			this._Innovation_Management_User = default(EntityRef<Innovation_Management_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_leave_allowance_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pk_leave_allowance_id
		{
			get
			{
				return this._pk_leave_allowance_id;
			}
			set
			{
				if ((this._pk_leave_allowance_id != value))
				{
					this.Onpk_leave_allowance_idChanging(value);
					this.SendPropertyChanging();
					this._pk_leave_allowance_id = value;
					this.SendPropertyChanged("pk_leave_allowance_id");
					this.Onpk_leave_allowance_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_user_id", DbType="Int")]
		public System.Nullable<int> fk_user_id
		{
			get
			{
				return this._fk_user_id;
			}
			set
			{
				if ((this._fk_user_id != value))
				{
					if (this._Innovation_Management_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_user_idChanging(value);
					this.SendPropertyChanging();
					this._fk_user_id = value;
					this.SendPropertyChanged("fk_user_id");
					this.Onfk_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_leave_type_id", DbType="Int")]
		public System.Nullable<int> fk_leave_type_id
		{
			get
			{
				return this._fk_leave_type_id;
			}
			set
			{
				if ((this._fk_leave_type_id != value))
				{
					if (this._Leave_Management_Leave_Type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_leave_type_idChanging(value);
					this.SendPropertyChanging();
					this._fk_leave_type_id = value;
					this.SendPropertyChanged("fk_leave_type_id");
					this.Onfk_leave_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allowance_year", DbType="NVarChar(50)")]
		public string allowance_year
		{
			get
			{
				return this._allowance_year;
			}
			set
			{
				if ((this._allowance_year != value))
				{
					this.Onallowance_yearChanging(value);
					this.SendPropertyChanging();
					this._allowance_year = value;
					this.SendPropertyChanged("allowance_year");
					this.Onallowance_yearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allowance_entitlement", DbType="Int")]
		public System.Nullable<int> allowance_entitlement
		{
			get
			{
				return this._allowance_entitlement;
			}
			set
			{
				if ((this._allowance_entitlement != value))
				{
					this.Onallowance_entitlementChanging(value);
					this.SendPropertyChanging();
					this._allowance_entitlement = value;
					this.SendPropertyChanged("allowance_entitlement");
					this.Onallowance_entitlementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allowance_taken", DbType="Float")]
		public System.Nullable<double> allowance_taken
		{
			get
			{
				return this._allowance_taken;
			}
			set
			{
				if ((this._allowance_taken != value))
				{
					this.Onallowance_takenChanging(value);
					this.SendPropertyChanging();
					this._allowance_taken = value;
					this.SendPropertyChanged("allowance_taken");
					this.Onallowance_takenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Leave_Management_Leave_Type_Leave_Management_Leave_Allowance", Storage="_Leave_Management_Leave_Type", ThisKey="fk_leave_type_id", OtherKey="pk_leave_type_id", IsForeignKey=true)]
		public Leave_Management_Leave_Type Leave_Management_Leave_Type
		{
			get
			{
				return this._Leave_Management_Leave_Type.Entity;
			}
			set
			{
				Leave_Management_Leave_Type previousValue = this._Leave_Management_Leave_Type.Entity;
				if (((previousValue != value) 
							|| (this._Leave_Management_Leave_Type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Leave_Management_Leave_Type.Entity = null;
						previousValue.Leave_Management_Leave_Allowances.Remove(this);
					}
					this._Leave_Management_Leave_Type.Entity = value;
					if ((value != null))
					{
						value.Leave_Management_Leave_Allowances.Add(this);
						this._fk_leave_type_id = value.pk_leave_type_id;
					}
					else
					{
						this._fk_leave_type_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Leave_Management_Leave_Type");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Leave_Allowance", Storage="_Innovation_Management_User", ThisKey="fk_user_id", OtherKey="pk_user_id", IsForeignKey=true)]
		public Innovation_Management_User Innovation_Management_User
		{
			get
			{
				return this._Innovation_Management_User.Entity;
			}
			set
			{
				Innovation_Management_User previousValue = this._Innovation_Management_User.Entity;
				if (((previousValue != value) 
							|| (this._Innovation_Management_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Innovation_Management_User.Entity = null;
						previousValue.Leave_Management_Leave_Allowances.Remove(this);
					}
					this._Innovation_Management_User.Entity = value;
					if ((value != null))
					{
						value.Leave_Management_Leave_Allowances.Add(this);
						this._fk_user_id = value.pk_user_id;
					}
					else
					{
						this._fk_user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Innovation_Management_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leave_Management_Leave_Taken")]
	public partial class Leave_Management_Leave_Taken : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pk_leave_taken_id;
		
		private System.Nullable<int> _fk_user_id;
		
		private System.Nullable<int> _fk_leave_type;
		
		private System.Nullable<System.DateTime> _leave_days;
		
		private System.Nullable<bool> _is_halfday;
		
		private System.Nullable<bool> _is_afternoon;
		
		private System.Nullable<int> _leave_status;
		
		private System.Nullable<int> _fk_approved_user_id;
		
		private EntityRef<Leave_Management_Leave_Type> _Leave_Management_Leave_Type;
		
		private EntityRef<Innovation_Management_User> _Innovation_Management_User;
		
		private EntityRef<Innovation_Management_User> _Innovation_Management_User1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_leave_taken_idChanging(int value);
    partial void Onpk_leave_taken_idChanged();
    partial void Onfk_user_idChanging(System.Nullable<int> value);
    partial void Onfk_user_idChanged();
    partial void Onfk_leave_typeChanging(System.Nullable<int> value);
    partial void Onfk_leave_typeChanged();
    partial void Onleave_daysChanging(System.Nullable<System.DateTime> value);
    partial void Onleave_daysChanged();
    partial void Onis_halfdayChanging(System.Nullable<bool> value);
    partial void Onis_halfdayChanged();
    partial void Onis_afternoonChanging(System.Nullable<bool> value);
    partial void Onis_afternoonChanged();
    partial void Onleave_statusChanging(System.Nullable<int> value);
    partial void Onleave_statusChanged();
    partial void Onfk_approved_user_idChanging(System.Nullable<int> value);
    partial void Onfk_approved_user_idChanged();
    #endregion
		
		public Leave_Management_Leave_Taken()
		{
			this._Leave_Management_Leave_Type = default(EntityRef<Leave_Management_Leave_Type>);
			this._Innovation_Management_User = default(EntityRef<Innovation_Management_User>);
			this._Innovation_Management_User1 = default(EntityRef<Innovation_Management_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_leave_taken_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pk_leave_taken_id
		{
			get
			{
				return this._pk_leave_taken_id;
			}
			set
			{
				if ((this._pk_leave_taken_id != value))
				{
					this.Onpk_leave_taken_idChanging(value);
					this.SendPropertyChanging();
					this._pk_leave_taken_id = value;
					this.SendPropertyChanged("pk_leave_taken_id");
					this.Onpk_leave_taken_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_user_id", DbType="Int")]
		public System.Nullable<int> fk_user_id
		{
			get
			{
				return this._fk_user_id;
			}
			set
			{
				if ((this._fk_user_id != value))
				{
					if (this._Innovation_Management_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_user_idChanging(value);
					this.SendPropertyChanging();
					this._fk_user_id = value;
					this.SendPropertyChanged("fk_user_id");
					this.Onfk_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_leave_type", DbType="Int")]
		public System.Nullable<int> fk_leave_type
		{
			get
			{
				return this._fk_leave_type;
			}
			set
			{
				if ((this._fk_leave_type != value))
				{
					if (this._Leave_Management_Leave_Type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_leave_typeChanging(value);
					this.SendPropertyChanging();
					this._fk_leave_type = value;
					this.SendPropertyChanged("fk_leave_type");
					this.Onfk_leave_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leave_days", DbType="Date")]
		public System.Nullable<System.DateTime> leave_days
		{
			get
			{
				return this._leave_days;
			}
			set
			{
				if ((this._leave_days != value))
				{
					this.Onleave_daysChanging(value);
					this.SendPropertyChanging();
					this._leave_days = value;
					this.SendPropertyChanged("leave_days");
					this.Onleave_daysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_halfday", DbType="Bit")]
		public System.Nullable<bool> is_halfday
		{
			get
			{
				return this._is_halfday;
			}
			set
			{
				if ((this._is_halfday != value))
				{
					this.Onis_halfdayChanging(value);
					this.SendPropertyChanging();
					this._is_halfday = value;
					this.SendPropertyChanged("is_halfday");
					this.Onis_halfdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_afternoon", DbType="Bit")]
		public System.Nullable<bool> is_afternoon
		{
			get
			{
				return this._is_afternoon;
			}
			set
			{
				if ((this._is_afternoon != value))
				{
					this.Onis_afternoonChanging(value);
					this.SendPropertyChanging();
					this._is_afternoon = value;
					this.SendPropertyChanged("is_afternoon");
					this.Onis_afternoonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leave_status", DbType="Int")]
		public System.Nullable<int> leave_status
		{
			get
			{
				return this._leave_status;
			}
			set
			{
				if ((this._leave_status != value))
				{
					this.Onleave_statusChanging(value);
					this.SendPropertyChanging();
					this._leave_status = value;
					this.SendPropertyChanged("leave_status");
					this.Onleave_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_approved_user_id", DbType="Int")]
		public System.Nullable<int> fk_approved_user_id
		{
			get
			{
				return this._fk_approved_user_id;
			}
			set
			{
				if ((this._fk_approved_user_id != value))
				{
					if (this._Innovation_Management_User1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_approved_user_idChanging(value);
					this.SendPropertyChanging();
					this._fk_approved_user_id = value;
					this.SendPropertyChanged("fk_approved_user_id");
					this.Onfk_approved_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Leave_Management_Leave_Type_Leave_Management_Leave_Taken", Storage="_Leave_Management_Leave_Type", ThisKey="fk_leave_type", OtherKey="pk_leave_type_id", IsForeignKey=true)]
		public Leave_Management_Leave_Type Leave_Management_Leave_Type
		{
			get
			{
				return this._Leave_Management_Leave_Type.Entity;
			}
			set
			{
				Leave_Management_Leave_Type previousValue = this._Leave_Management_Leave_Type.Entity;
				if (((previousValue != value) 
							|| (this._Leave_Management_Leave_Type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Leave_Management_Leave_Type.Entity = null;
						previousValue.Leave_Management_Leave_Takens.Remove(this);
					}
					this._Leave_Management_Leave_Type.Entity = value;
					if ((value != null))
					{
						value.Leave_Management_Leave_Takens.Add(this);
						this._fk_leave_type = value.pk_leave_type_id;
					}
					else
					{
						this._fk_leave_type = default(Nullable<int>);
					}
					this.SendPropertyChanged("Leave_Management_Leave_Type");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Leave_Taken", Storage="_Innovation_Management_User", ThisKey="fk_user_id", OtherKey="pk_user_id", IsForeignKey=true)]
		public Innovation_Management_User Innovation_Management_User
		{
			get
			{
				return this._Innovation_Management_User.Entity;
			}
			set
			{
				Innovation_Management_User previousValue = this._Innovation_Management_User.Entity;
				if (((previousValue != value) 
							|| (this._Innovation_Management_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Innovation_Management_User.Entity = null;
						previousValue.Leave_Management_Leave_Takens.Remove(this);
					}
					this._Innovation_Management_User.Entity = value;
					if ((value != null))
					{
						value.Leave_Management_Leave_Takens.Add(this);
						this._fk_user_id = value.pk_user_id;
					}
					else
					{
						this._fk_user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Innovation_Management_User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Leave_Taken1", Storage="_Innovation_Management_User1", ThisKey="fk_approved_user_id", OtherKey="pk_user_id", IsForeignKey=true)]
		public Innovation_Management_User Innovation_Management_User1
		{
			get
			{
				return this._Innovation_Management_User1.Entity;
			}
			set
			{
				Innovation_Management_User previousValue = this._Innovation_Management_User1.Entity;
				if (((previousValue != value) 
							|| (this._Innovation_Management_User1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Innovation_Management_User1.Entity = null;
						previousValue.Leave_Management_Leave_Takens1.Remove(this);
					}
					this._Innovation_Management_User1.Entity = value;
					if ((value != null))
					{
						value.Leave_Management_Leave_Takens1.Add(this);
						this._fk_approved_user_id = value.pk_user_id;
					}
					else
					{
						this._fk_approved_user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Innovation_Management_User1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Innovation_Management_User")]
	public partial class Innovation_Management_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pk_user_id;
		
		private string _user_firstname;
		
		private string _user_lastname;
		
		private string _user_name;
		
		private string _user_email;
		
		private string _user_password;
		
		private string _user_area;
		
		private System.Nullable<int> _fk_assigned_country;
		
		private string _user_picture;
		
		private System.Nullable<bool> _user_isadmin;
		
		private System.Nullable<bool> _user_isdeleted;
		
		private System.Nullable<bool> _special_permission_1;
		
		private EntitySet<Leave_Management_Approval_Matrix> _Leave_Management_Approval_Matrixes;
		
		private EntitySet<Leave_Management_Approval_Matrix> _Leave_Management_Approval_Matrixes1;
		
		private EntitySet<Leave_Management_Leave_Allowance> _Leave_Management_Leave_Allowances;
		
		private EntitySet<Leave_Management_Leave_Taken> _Leave_Management_Leave_Takens;
		
		private EntitySet<Leave_Management_Leave_Taken> _Leave_Management_Leave_Takens1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_user_idChanging(int value);
    partial void Onpk_user_idChanged();
    partial void Onuser_firstnameChanging(string value);
    partial void Onuser_firstnameChanged();
    partial void Onuser_lastnameChanging(string value);
    partial void Onuser_lastnameChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Onuser_passwordChanging(string value);
    partial void Onuser_passwordChanged();
    partial void Onuser_areaChanging(string value);
    partial void Onuser_areaChanged();
    partial void Onfk_assigned_countryChanging(System.Nullable<int> value);
    partial void Onfk_assigned_countryChanged();
    partial void Onuser_pictureChanging(string value);
    partial void Onuser_pictureChanged();
    partial void Onuser_isadminChanging(System.Nullable<bool> value);
    partial void Onuser_isadminChanged();
    partial void Onuser_isdeletedChanging(System.Nullable<bool> value);
    partial void Onuser_isdeletedChanged();
    partial void Onspecial_permission_1Changing(System.Nullable<bool> value);
    partial void Onspecial_permission_1Changed();
    #endregion
		
		public Innovation_Management_User()
		{
			this._Leave_Management_Approval_Matrixes = new EntitySet<Leave_Management_Approval_Matrix>(new Action<Leave_Management_Approval_Matrix>(this.attach_Leave_Management_Approval_Matrixes), new Action<Leave_Management_Approval_Matrix>(this.detach_Leave_Management_Approval_Matrixes));
			this._Leave_Management_Approval_Matrixes1 = new EntitySet<Leave_Management_Approval_Matrix>(new Action<Leave_Management_Approval_Matrix>(this.attach_Leave_Management_Approval_Matrixes1), new Action<Leave_Management_Approval_Matrix>(this.detach_Leave_Management_Approval_Matrixes1));
			this._Leave_Management_Leave_Allowances = new EntitySet<Leave_Management_Leave_Allowance>(new Action<Leave_Management_Leave_Allowance>(this.attach_Leave_Management_Leave_Allowances), new Action<Leave_Management_Leave_Allowance>(this.detach_Leave_Management_Leave_Allowances));
			this._Leave_Management_Leave_Takens = new EntitySet<Leave_Management_Leave_Taken>(new Action<Leave_Management_Leave_Taken>(this.attach_Leave_Management_Leave_Takens), new Action<Leave_Management_Leave_Taken>(this.detach_Leave_Management_Leave_Takens));
			this._Leave_Management_Leave_Takens1 = new EntitySet<Leave_Management_Leave_Taken>(new Action<Leave_Management_Leave_Taken>(this.attach_Leave_Management_Leave_Takens1), new Action<Leave_Management_Leave_Taken>(this.detach_Leave_Management_Leave_Takens1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pk_user_id
		{
			get
			{
				return this._pk_user_id;
			}
			set
			{
				if ((this._pk_user_id != value))
				{
					this.Onpk_user_idChanging(value);
					this.SendPropertyChanging();
					this._pk_user_id = value;
					this.SendPropertyChanged("pk_user_id");
					this.Onpk_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_firstname", DbType="NVarChar(255)")]
		public string user_firstname
		{
			get
			{
				return this._user_firstname;
			}
			set
			{
				if ((this._user_firstname != value))
				{
					this.Onuser_firstnameChanging(value);
					this.SendPropertyChanging();
					this._user_firstname = value;
					this.SendPropertyChanged("user_firstname");
					this.Onuser_firstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_lastname", DbType="NVarChar(255)")]
		public string user_lastname
		{
			get
			{
				return this._user_lastname;
			}
			set
			{
				if ((this._user_lastname != value))
				{
					this.Onuser_lastnameChanging(value);
					this.SendPropertyChanging();
					this._user_lastname = value;
					this.SendPropertyChanged("user_lastname");
					this.Onuser_lastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="NVarChar(50)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="NVarChar(50)")]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this.Onuser_passwordChanging(value);
					this.SendPropertyChanging();
					this._user_password = value;
					this.SendPropertyChanged("user_password");
					this.Onuser_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_area", DbType="NVarChar(255)")]
		public string user_area
		{
			get
			{
				return this._user_area;
			}
			set
			{
				if ((this._user_area != value))
				{
					this.Onuser_areaChanging(value);
					this.SendPropertyChanging();
					this._user_area = value;
					this.SendPropertyChanged("user_area");
					this.Onuser_areaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_assigned_country", DbType="Int")]
		public System.Nullable<int> fk_assigned_country
		{
			get
			{
				return this._fk_assigned_country;
			}
			set
			{
				if ((this._fk_assigned_country != value))
				{
					this.Onfk_assigned_countryChanging(value);
					this.SendPropertyChanging();
					this._fk_assigned_country = value;
					this.SendPropertyChanged("fk_assigned_country");
					this.Onfk_assigned_countryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_picture", DbType="NVarChar(MAX)")]
		public string user_picture
		{
			get
			{
				return this._user_picture;
			}
			set
			{
				if ((this._user_picture != value))
				{
					this.Onuser_pictureChanging(value);
					this.SendPropertyChanging();
					this._user_picture = value;
					this.SendPropertyChanged("user_picture");
					this.Onuser_pictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_isadmin", DbType="Bit")]
		public System.Nullable<bool> user_isadmin
		{
			get
			{
				return this._user_isadmin;
			}
			set
			{
				if ((this._user_isadmin != value))
				{
					this.Onuser_isadminChanging(value);
					this.SendPropertyChanging();
					this._user_isadmin = value;
					this.SendPropertyChanged("user_isadmin");
					this.Onuser_isadminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_isdeleted", DbType="Bit")]
		public System.Nullable<bool> user_isdeleted
		{
			get
			{
				return this._user_isdeleted;
			}
			set
			{
				if ((this._user_isdeleted != value))
				{
					this.Onuser_isdeletedChanging(value);
					this.SendPropertyChanging();
					this._user_isdeleted = value;
					this.SendPropertyChanged("user_isdeleted");
					this.Onuser_isdeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_special_permission_1", DbType="Bit")]
		public System.Nullable<bool> special_permission_1
		{
			get
			{
				return this._special_permission_1;
			}
			set
			{
				if ((this._special_permission_1 != value))
				{
					this.Onspecial_permission_1Changing(value);
					this.SendPropertyChanging();
					this._special_permission_1 = value;
					this.SendPropertyChanged("special_permission_1");
					this.Onspecial_permission_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Approval_Matrix", Storage="_Leave_Management_Approval_Matrixes", ThisKey="pk_user_id", OtherKey="fk_requestor_id")]
		public EntitySet<Leave_Management_Approval_Matrix> Leave_Management_Approval_Matrixes
		{
			get
			{
				return this._Leave_Management_Approval_Matrixes;
			}
			set
			{
				this._Leave_Management_Approval_Matrixes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Approval_Matrix1", Storage="_Leave_Management_Approval_Matrixes1", ThisKey="pk_user_id", OtherKey="fk_approver_id")]
		public EntitySet<Leave_Management_Approval_Matrix> Leave_Management_Approval_Matrixes1
		{
			get
			{
				return this._Leave_Management_Approval_Matrixes1;
			}
			set
			{
				this._Leave_Management_Approval_Matrixes1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Leave_Allowance", Storage="_Leave_Management_Leave_Allowances", ThisKey="pk_user_id", OtherKey="fk_user_id")]
		public EntitySet<Leave_Management_Leave_Allowance> Leave_Management_Leave_Allowances
		{
			get
			{
				return this._Leave_Management_Leave_Allowances;
			}
			set
			{
				this._Leave_Management_Leave_Allowances.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Leave_Taken", Storage="_Leave_Management_Leave_Takens", ThisKey="pk_user_id", OtherKey="fk_user_id")]
		public EntitySet<Leave_Management_Leave_Taken> Leave_Management_Leave_Takens
		{
			get
			{
				return this._Leave_Management_Leave_Takens;
			}
			set
			{
				this._Leave_Management_Leave_Takens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Innovation_Management_User_Leave_Management_Leave_Taken1", Storage="_Leave_Management_Leave_Takens1", ThisKey="pk_user_id", OtherKey="fk_approved_user_id")]
		public EntitySet<Leave_Management_Leave_Taken> Leave_Management_Leave_Takens1
		{
			get
			{
				return this._Leave_Management_Leave_Takens1;
			}
			set
			{
				this._Leave_Management_Leave_Takens1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Leave_Management_Approval_Matrixes(Leave_Management_Approval_Matrix entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User = this;
		}
		
		private void detach_Leave_Management_Approval_Matrixes(Leave_Management_Approval_Matrix entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User = null;
		}
		
		private void attach_Leave_Management_Approval_Matrixes1(Leave_Management_Approval_Matrix entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User1 = this;
		}
		
		private void detach_Leave_Management_Approval_Matrixes1(Leave_Management_Approval_Matrix entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User1 = null;
		}
		
		private void attach_Leave_Management_Leave_Allowances(Leave_Management_Leave_Allowance entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User = this;
		}
		
		private void detach_Leave_Management_Leave_Allowances(Leave_Management_Leave_Allowance entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User = null;
		}
		
		private void attach_Leave_Management_Leave_Takens(Leave_Management_Leave_Taken entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User = this;
		}
		
		private void detach_Leave_Management_Leave_Takens(Leave_Management_Leave_Taken entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User = null;
		}
		
		private void attach_Leave_Management_Leave_Takens1(Leave_Management_Leave_Taken entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User1 = this;
		}
		
		private void detach_Leave_Management_Leave_Takens1(Leave_Management_Leave_Taken entity)
		{
			this.SendPropertyChanging();
			entity.Innovation_Management_User1 = null;
		}
	}
}
#pragma warning restore 1591
